#!/usr/bin/env bash
# This script displays 'To infinity and beyond' every 2 seconds on an infinite
# loop
trap 'echo I am invincible!!!' TERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
