#!/usr/bin/env bash
# This script prints "Holberton School" 10 times and "Hi" on the 9th iteration
i=0
while [ "$i" -ne 10 ]; do
	echo "Holberton School"
	if [ "$i" -eq 8 ]
	then
		echo "Hi"
	fi
	let "i+=1"
done
