#!/usr/bin/env bash
# This script loops 1 to 10, on the 4th iteration it prints "bad luck", on the
# 8th iteration it prints "good luck", and prints "Holberton School" for every
# other iteration.
i=1
while [ "$i" -le 10 ]; do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	let "i+=1"
done
