#!/usr/bin/env bash
# This script prints numbers 1 to 20, but if the number is 4, print "bad luck
# from China", if the number is 9, print "bad luck from Japan", if the number
# is 17, print "bad luck from Italy"
i=1
while [ "$i" -le 20 ]; do
	echo $i
	case "$i" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	let "i+=1"
done
