#!/usr/bin/env bash
# This script checks if the file "holbertonschool" exists, empty, and if it is
# a regular file
file="./holbertonschool"
if [ -e "$file" ]
then
	echo "holbertonschool file exists"
	if [ -s "$file" ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f "$file" ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
